version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq_flashSale'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/root/develop/log/rabbitMQ
        - ~/.docker-conf/rabbitmq/log/:/root/develop/log/rabbitMQ
    networks:
        - rabbitmq_go_net

  mysql:
    image: mysql:5.7.41-oracle
    container_name: 'mysql_flashSale'
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    networks:
      - rabbitmq_go_net

  redis:
  image: redis:6.2-alpine
  restart: always
  ports:
    - 6379:6379
  command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
  volumes: 
    - cache:/data
  networks:
      - rabbitmq_go_net


networks:
  rabbitmq_go_net:
    driver: bridge
